TelefonRehberi.WebUI/Controllers/DepartmanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TelefonRehberi.Data.Abstract;
using TelefonRehberi.Entity;

namespace TelefonRehberi.WebUI.Controllers
{

    public class DepartmanController : Controller
    {
        private readonly IDepartmanRepository _departmanRepository;
        private readonly ICalisanRepository _calisanRepository;
      
       
        public DepartmanController(IDepartmanRepository departmanRepo , ICalisanRepository calisanRepo )
        {
            
            _departmanRepository = departmanRepo;
            _calisanRepository = calisanRepo;
            
            
        }

        public IActionResult Index()
        {
            return View(_departmanRepository.GetAll());
        }

        [HttpGet]
        public IActionResult Ekle()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Ekle(Departman departman)
        {
            if (ModelState.IsValid)
            {
                _departmanRepository.AddDepartman(departman);
                TempData["message"] = $"{departman.DepartmanAdi} departman olarak eklendi.";
                return RedirectToAction("Index");
            }
            return View(departman);
        }

        public IActionResult Duzenle(int id)
        {
            return View(_departmanRepository.GetById(id));
        }

        [HttpPost]
        public IActionResult Duzenle(Departman departman)
        {
            if (ModelState.IsValid)
            {
                _departmanRepository.UpdateDepartman(departman);
                TempData["message"] = $"{departman.DepartmanAdi} güncellendi.";
                return RedirectToAction("Index");
            }
            
            return View(departman);
        }

        [HttpGet]
        public IActionResult Sil (int id)
        {
            return View(_departmanRepository.GetById(id));
        }



        [HttpPost, ActionName("Sil")]

        public IActionResult SilOnayla(int departmanId)
        {
            var b = _departmanRepository.GetAll().Where(i => i.DepartmanId == departmanId).Include(i => i.Calisanlar).SingleOrDefault();

            if(b.Calisanlar.Count() == 0)
            {
                _departmanRepository.DeleteDepartman(departmanId);
                TempData["message"] = $"{departmanId} numaralı departman silindi.";
                return RedirectToAction("Index");
            }

            TempData["message"] = $"{departmanId} numaralı Bu departmanı silemezsiniz! Bu departmanda çalışanlar var.";
            return RedirectToAction("Index");
        }


    }
}

TelefonRehberi.WebUI/Views/Departman/Duzenle.cshtml
@model Departman
@{
    ViewData["Title"] = "Duzenle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Departman Düzenle</h2>

<div class="form">
    <form class="form-validate form-horizontal" id="feedback_form" method="post" action="/Departman/Duzenle/" enctype="multipart/form-data">
        <div class="form-group ">
            <input type="hidden" asp-for="DepartmanId" />
            <label for="DepartmanAdi" class="control-label col-lg-2">Departman Adı <span class="required">*</span></label>
            <div class="col-lg-10">
                <input class="form-control" id="DepartmanAdi" name="DepartmanAdi" type="text" required value="@Model.DepartmanAdi" />
            </div>
           
        </div>
       


        <div class="form-group">
            <div class="col-lg-offset-2 col-lg-10">
                <button class="btn btn-primary" type="submit">Düzenle</button>
                <button class="btn btn-default" type="button"><a href="/Departman/Index">İptal</a></button>
            </div>
        </div>
    </form>
</div>

TelefonRehberi.WebUI/Views/Departman/Ekle.cshtml
@{
    ViewData["Title"] = "Ekle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Çalışan Kayıt Ekle</h2>

<div class="form">
    <form class="form-validate form-horizontal" id="feedback_form" method="post" action="/Departman/Ekle/" enctype="multipart/form-data">
        <div class="form-group ">
            <label for="DepartmanAdi" class="control-label col-lg-2">Departman Adı <span class="required">*</span></label>
            <div class="col-lg-10">
                <input class="form-control" id="DepartmanAdi" name="DepartmanAdi" type="text" required />
            </div>        
        </div>
   
        <div class="form-group">
            <div class="col-lg-offset-2 col-lg-10">
                <button class="btn btn-primary" type="submit">Ekle</button>
                <button class="btn btn-default" type="button"><a href="/Departman/Index">İptal</a></button>
            </div>
        </div>
    </form>
</div>

TelefonRehberi.WebUI/Views/Departman/Index.cshtml
@model IEnumerable<Departman>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<script>
    $(document).ready(function () {
        $('#table_id').DataTable(
            {
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Turkish.json"
                }
            }
        );
    });
</script>


<h2>Departman Kayıtları</h2>

<a class="btn btn-outline-dark mt-2 mb-2" href="/Departman/Ekle/">Yeni Departman Ekle</a>


<table class="table table-striped table-sm" id="table_id">
    <thead>
        <tr>
            <th>Departman Id</th>
            <th>Departman Adı</th>
            <th>İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.DepartmanId</td>
                <td>@item.DepartmanAdi</td>
               
                <td><a class="btn btn-primary btn-sm" href="/Departman/Duzenle/@item.DepartmanId">Düzenle</a> | <a class="btn btn-danger btn-sm" href="/Departman/Sil/@item.DepartmanId">Sil</a></td>
            </tr>
        }

    </tbody>
</table>

TelefonRehberi.WebUI/Views/Departman/Sil.cshtml
@model Departman
@{
    ViewData["Title"] = "Sil";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<h2>
    <b>@Model.DepartmanAdi </b> isimli departmanı silmek istiyor musunuz ?
</h2>

<form asp-controller="Departman" asp-action="Sil" method="post">
    <input type="hidden" asp-for="DepartmanId" />

    <button type="submit" class="btn btn-primary">Sil</button>
</form>