TelefonRehberi.WebUI/Controllers/CalisanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TelefonRehberi.Data.Abstract;
using TelefonRehberi.Entity;

namespace TelefonRehberi.WebUI.Controllers
{
    public class CalisanController : Controller
    {
        private readonly ICalisanRepository _calisanRepository;
        private readonly IDepartmanRepository _departmanRepository;   
        public CalisanController(ICalisanRepository calisanRepo , IDepartmanRepository departmanRepo)
        {
            _calisanRepository = calisanRepo;
            _departmanRepository = departmanRepo;
        }

        public IActionResult Index()
        {
            return View(_calisanRepository.GetAll().Include(i=>i.Departman));
        }

        public IActionResult Ekle()
        {
            ViewBag.DepartmanId = new SelectList(_departmanRepository.GetAll(), "DepartmanId", "DepartmanAdi");
            ViewBag.YoneticiId = new SelectList(_calisanRepository.GetAll(), "YoneticiId", "CalisanAdi");
            return View();
        }

        [HttpPost]
        public IActionResult Ekle(Calisan calisan)
        {
            if (ModelState.IsValid)
            {
                _calisanRepository.AddCalisan(calisan);
                TempData["message"] = $"{calisan.CalisanAdi } {calisan.CalisanSoyadi} çalışan olarak eklendi.";
                return RedirectToAction("Index");
            }

            ViewBag.DepartmanId = new SelectList(_departmanRepository.GetAll(), "DepartmanId", "DepartmanAdi");
            ViewBag.YoneticiId = new SelectList(_calisanRepository.GetAll(), "YoneticiId", "CalisanAdi");
            return View(calisan);
        }
        [HttpGet]
        public IActionResult Duzenle(int id)
        {
            ViewBag.DepartmanId = new SelectList(_departmanRepository.GetAll(), "DepartmanId", "DepartmanAdi");
            ViewBag.YoneticiId = new SelectList(_calisanRepository.GetAll(), "YoneticiId", "CalisanAdi");

            return View(_calisanRepository.GetById(id));
        }
        [HttpPost]
        public IActionResult Duzenle(Calisan calisan)
        {
            if (ModelState.IsValid)
            {
                _calisanRepository.UpdateCalisan(calisan);
                TempData["message"] = $"{calisan.CalisanAdi} {calisan.CalisanSoyadi} güncellendi.";
                return RedirectToAction("Index");
            }
            ViewBag.YoneticiId = new SelectList(_calisanRepository.GetAll(), "YoneticiId", "CalisanAdi");
            return View(calisan);
        }

        [HttpGet]
        public IActionResult Sil(int id)
        {
            return View(_calisanRepository.GetById(id));
        }

        [HttpPost,ActionName("Sil")]

        public IActionResult SilOnayla(int calisanId)
        {
            _calisanRepository.DeleteCalisan(calisanId);
            TempData["message"] = $"{calisanId} numaralı çalışan silindi.";
            return RedirectToAction("Index");  
        }
    }
}

TelefonRehberi.WebUI/Views/Calisan/Duzenle.cshtml
@model Calisan
@{
    ViewData["Title"] = "Duzenle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Çalışan Düzenle</h2>

<div class="form">
    <form class="form-validate form-horizontal" id="feedback_form" method="post" action="/Calisan/Duzenle/" enctype="multipart/form-data">
        <div class="form-group ">
            <input type="hidden" asp-for="CalisanId"/>
            <label for="CalisanAdi" class="control-label col-lg-2">Çalışan Adı <span class="required">*</span></label>
            <div class="col-lg-10">
                <input class="form-control" id="CalisanAdi" name="CalisanAdi" type="text" required value="@Model.CalisanAdi" />
            </div>
            <label for="CalisanSoyadi" class="control-label col-lg-2">Çalışan Soyadı <span class="required">*</span></label>
            <div class="col-lg-10">
                <input class="form-control" id="CalisanSoyadi" name="CalisanSoyadi" type="text" required value="@Model.CalisanSoyadi" />
            </div>
            <label for="Telefon" class="control-label col-lg-2">Çalışan Telefonu <span class="required" >*</span></label>
            <div class="col-lg-10">
                <input class="form-control" id="Telefon" name="Telefon" type="text" required value="@Model.Telefon" />
            </div>
        </div>
        <div class="form-group ">
            <label for="Departman" class="control-label col-lg-2">Departman</label>
            <div class="col-lg-10">
                @Html.DropDownList("DepartmanId", null, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group ">
            <label for="Yonetici" class="control-label col-lg-2">Yonetici Id </label>
            <div class="col-lg-10">
                @Html.DropDownList("YoneticiId", null, new { @class = "form-control" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-lg-offset-2 col-lg-10">
                <button class="btn btn-primary" type="submit">Düzenle</button>
                <button class="btn btn-default" type="button"><a href="/Calisan/Index">İptal</a></button>
            </div>
        </div>
    </form>
</div>

TelefonRehberi.WebUI/Views/Calisan/Ekle.cshtml
@{
    ViewData["Title"] = "Ekle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Çalışan Kayıt Ekle</h2>

<div class="form">
    <form class="form-validate form-horizontal" id="feedback_form" method="post" action="/Calisan/Ekle/" enctype="multipart/form-data">
        <div class="form-group ">
            <label for="CalisanAdi" class="control-label col-lg-2">Çalışan Adı <span class="required">*</span></label>
            <div class="col-lg-10">
                <input class="form-control" id="CalisanAdi" name="CalisanAdi" type="text" required />
            </div>
            <label for="CalisanSoyadi" class="control-label col-lg-2">Çalışan Soyadı <span class="required">*</span></label>
            <div class="col-lg-10">
                <input class="form-control" id="CalisanSoyadi" name="CalisanSoyadi" type="text" required />
            </div>
            <label for="Telefon" class="control-label col-lg-2">Çalışan Telefonu <span class="required">*</span></label>
            <div class="col-lg-10">
                <input class="form-control" id="Telefon" name="Telefon" type="text" required />
            </div>
        </div>
        <div class="form-group ">
            <label for="Departman" class="control-label col-lg-2">Departman</label>
            <div class="col-lg-10">
                @Html.DropDownList("DepartmanId", null, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group ">
            <label for="Yonetici" class="control-label col-lg-2">Yonetici Id </label>
            <div class="col-lg-10">
                @Html.DropDownList("YoneticiId", null, new { @class = "form-control" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-lg-offset-2 col-lg-10">
                <button class="btn btn-primary" type="submit">Ekle</button>
                <button class="btn btn-default" type="button"><a href="/Calisan/Index">İptal</a></button>
            </div>
        </div>
    </form>
</div>

TelefonRehberi.WebUI/Views/Calisan/Index.cshtml
@model IEnumerable<Calisan>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<script>
  $(document).ready( function () {
      $('#table_id').DataTable(
          {
              "language": {
                  "url" : "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Turkish.json"
              }
          }
      );
} );
</script>

<h2>Çalışan Kayıtları</h2>

<a class="btn btn-outline-dark mt-2 mb-2" href="/Calisan/Ekle/">Yeni Çalışan Ekle</a>


    <table class="table table-striped table-sm" id="table_id">
        <thead>
            <tr>
                <th>Çalışan Id</th>
                <th>Ad</th>
                <th>Soyad</th>
                <th>Departman</th>
                <th>Telefon</th>
                <th>Yönetici Id</th>
                <th>İşlemler</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.CalisanId</td>
                    <td>@item.CalisanAdi</td>
                    <td>@item.CalisanSoyadi</td>
                    <td>@item.Departman.DepartmanAdi</td>
                    <td>@item.Telefon</td>
                    <td>@item.YoneticiId</td>
                    <td><a class="btn btn-primary btn-sm" href="/Calisan/Duzenle/@item.CalisanId">Düzenle</a> | <a class="btn btn-danger btn-sm" href="/Calisan/Sil/@item.CalisanId">Sil</a></td>
                </tr>
            }

        </tbody>
    </table>

TelefonRehberi.WebUI/Views/Calisan/Sil.cshtml
@model Calisan
@{
    ViewData["Title"] = "Sil";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>
    <b>@Model.CalisanAdi @Model.CalisanSoyadi </b> isimli çalışanı silmek istiyor musunuz ? 
</h2>

<form asp-controller="Calisan" asp-action="Sil" method="post">
    <input type="hidden" asp-for="CalisanId"/>

    <button type="submit" class="btn btn-primary">Sil</button>
</form>